version: "2"

linters:
  default: all
  disable:
    - wsl
    - ireturn
    - godox
    - exhaustruct
    - wrapcheck

  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 4
    funlen:
      lines: 83
      statements: -1
    nlreturn:
      block-size: 2
    depguard:
      rules:
        main:
          files:
            - "$all"
            - "!$test"
          allow:
            - "$gostd"
            - "github.com/SharkByteSoftware/go-snk"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false

output:
  sort-order:
    - linter
    - severity
    - file

  show-stats: true

run:
  timeout: 30s
  tests: false
  allow-parallel-runners: true
